# nixpacks.toml - Build configuration for Railway

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
# Let's rely on `npm ci` to create a clean install. 
# Nixpacks will handle caching node_modules correctly if we let it.
cmds = ["npm ci"]

[phases.build]
# Removed --force and --no-cache to let Turborepo and Nixpacks use their
# default, optimized caching strategies.
cmds = ["npx turbo build --filter=@finito/web"]

[start]
cmd = "cd apps/web && npm start"

[variables]
# We only need NODE_ENV here. Let's remove the NIXPACKS_NO_CACHE
# to avoid the conflict.
NODE_ENV = "production"