# nixpacks.toml - Build configuration for Railway

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
# Clear any existing cache and do a clean install
cmds = [
  "rm -rf node_modules .turbo apps/web/.next",
  "npm ci --force"
]

[phases.build]
# Build without turbo cache
cmds = ["npx turbo build --filter=@finito/web --force --no-cache"]

[start]
cmd = "cd apps/web && npm start"

[variables]
NODE_ENV = "production"
NIXPACKS_NO_CACHE = "1"