# nixpacks.toml - Build configuration for Railway

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci --force"]

[phases.build]
cmds = ["npx turbo build --filter=@finito/web --force"]

[start]
cmd = "cd apps/web && npm start"

[variables]
NODE_ENV = "production"