# railway.toml - Monorepo deployment configuration for Railway

[build]
builder = "nixpacks"
# buildCommand removed - using nixpacks.toml phases instead

[deploy]
startCommand = "cd apps/web && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
# Health check endpoint created in the web app
path = "/api/health"
# Faster failure detection for production deployment
timeout = 20
interval = 30
retries = 5

# Environment variables that Railway will use
[env]
# Production environment
NODE_ENV = "production"