# railway.toml - Monorepo deployment configuration

[build]
# Use Nixpacks for automatic Node.js detection and optimization
builder = "nixpacks"
# Build only the web app and its dependencies using Turbo
buildCommand = "npm install && npx turbo build --filter=@finito/web"

[deploy]
# Start the web application with explicit port binding for Railway
startCommand = "cd apps/web && npx next start -p $PORT"
# Railway will automatically handle restarts on failure
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
# Health check endpoint created in the web app
path = "/api/health"
# Faster failure detection for production deployment
timeout = 20
interval = 30
retries = 5

# Environment variables that Railway will use
[env]
# Production environment
NODE_ENV = "production"